### ISSUE TITLE
Do the rest

### ISSUE THREAD

**Issue by baitun** [rudensergey/darkroom#19]
- [x] Section `Introducing Darkroom Plus`
- [x] Section `Welcome to The Darkroom Podcast`
- [x] Interactive button `View all podcasts`
- [x] Footer
- [x] Get rid of Google Fonts, make it local

**Comment by rudensergey** [comment]
<img width="443" alt="Screenshot 2019-07-30 at 18 27 36" src="https://user-images.githubusercontent.com/44585564/62142876-c0a1b480-b2f7-11e9-9916-0517f7646ebe.png">
How I can rewrite this snippet of code? These two pseudo objects stuck me because they are the same, but when I try to create new selector with:height width margin content - it break down

**Comment by rudensergey** [comment]
Done, send a pull request to you for review
